extract:
- filepath: D:\Models\RSM_Visualizer\visualizer\simwrapper\data\external\donor_model\report
  test_size: null
  data:
  - households.csv
  - individualTrips.csv
  - jointTrips.csv
  - transit_onoff.csv
  - internalExternalTrips.csv
  - airportCBXTrips.csv
  - airportSANTrips.csv
  - commercialVehicleTrips.csv
  - crossBorderTrips.csv
  - externalInternalTrips.csv
  - externalExternalTrips.csv
  - truckTrips.csv
  - visitorTrips.csv
  - hwyload_*.csv
  - hwyTcad.csv
- filepath: D:\Models\RSM_Visualizer\visualizer\simwrapper\data\external\donor_model\input
  test_size: null
  data:
  - households_org.csv
transform:
  processor: config/processor_donor_model.csv
  summarizer: config/expressions_donor_model.csv
  steps:
  - name: step_0
    process: true
  - name: step_1
    concat:
    - table_name: trips
      include:
      - individualTrips
      - jointTrips
      - internalExternalTrips
      - airportCBXTrips
      - airportSANTrips
      - commercialVehicleTrips
      - crossBorderTrips
      - externalInternalTrips
      - externalExternalTrips
      - truckTrips
      - visitorTrips
    - table_name: highway_load
      include:
      - hwyload_*
    process: true
  - name: step_2
    merge:
    - table_name: network
      include:
      - highway_network
      - highway_load
      merge_cols:
      - - ID
        - timePeriod
      - - ID1
        - timePeriod
      merge_type: left
    process: true
  - name: step_3
    summarize: true
    process: true
load:
  outdir: D:\Models\RSM_Visualizer\visualizer\simwrapper\data\processed\donor_model\
  empty_fill: 0
